### PR TITLE
fix: visualize diffs of PlantUML descriptions which include both renaming and changes

### LINKED ISSUE #156: fix: visualize diffs of PlantUML descriptions which include both renaming and changes
from #107 
To make this extension visualize https://github.com/WillBooster/plantuml-visualizer/pull/106/files

### PR DESCRIPTION
**Pull request by kumachan-mis**
close #156 
will support #105 #106 #266

### CODE REVIEW

File: src/finder/GitHubFinder.ts [hunk 1]
```diff
@@ -111,6 +118,28 @@ export class GitHubPullRequestDiffFinder implements DiffFinder {
...
+        filePaths.push(filePath);
+        filePath = '';
+      } else {
+        filePath += separator;
+      }
+    }
+    console.log(filePaths);
+    if (filePaths.length == 1) return [filePaths[0], filePaths[0]];
+    if (filePaths.length == 2) return [filePaths[0], filePaths[1]];
+    else return ['', ''];
```
Comment (exKAZUu) [inline src/finder/GitHubFinder.ts]: `else` should be omitted.

File: src/finder/GitHubFinder.ts [hunk 2]
```diff
@@ -111,6 +118,28 @@ export class GitHubPullRequestDiffFinder implements DiffFinder {
...
+    for (const fragment of fragments) {
+      filePath += fragment;
+      if (filePath.match(/^.*\.(plantuml|pu|puml)$/)) {
+        filePaths.push(filePath);
+        filePath = '';
+      } else {
+        filePath += separator;
+      }
+    }
+    console.log(filePaths);
```
Comment (exKAZUu) [inline src/finder/GitHubFinder.ts]: Could you remove this debug code?

File: src/finder/GitHubFinder.ts [hunk 3]
```diff
@@ -74,9 +74,9 @@ export class GitHubPullRequestDiffFinder implements DiffFinder {
     return diffs;
   }
 
-  private getBaseHeadBranchNames($root: JQuery<Node>): string[] {
+  private getBaseHeadBranchNames($root: JQuery<Node>): [string, string] {
```
Comment (exKAZUu) [inline src/finder/GitHubFinder.ts]: :+1:

File: src/finder/GitHubFinder.ts [hunk 4]
```diff
@@ -74,9 +74,9 @@ export class GitHubPullRequestDiffFinder implements DiffFinder {
...
     const tableObjectTagName = 'div.TableObject-item.TableObject-item--primary';
-    const getTagName = (baseOrHead: string): string =>
+    const getTagName = (baseOrHead: 'base' | 'head'): string =>
```
Comment (exKAZUu) [inline src/finder/GitHubFinder.ts]: :+1:
